# Лабораторная работа №1
## Выполнил студент группы БВТ2001 Разумов Игорь Вячеславович
### Задание 1

In [16]:
print("Hello, world!")

Hello, world!


### Задание 2

In [29]:
from random import randint
import numpy as np
m, n , min_limit, max_limit = map(int, input("Введите числа:").split()) 
a = []
for i in range(m*n):
    a.append(randint(min_limit,max_limit))
counter = 0


counter = 0
a_np = np.zeros((m,n))
for i in range (m):
    for j in range (n):
        a_np[i][j] = a[counter]
        counter += 1
print ("Numpy матрица")
print(a_np)

Введите числа:4 10 1 34
Numpy матрица
[[ 7. 21. 28.  9. 28. 13.  8.  9. 10. 20.]
 [ 8.  8. 18. 32. 22.  2.  3. 34. 32.  6.]
 [20. 20. 33. 19. 15. 34.  5. 33.  7.  4.]
 [22. 20. 11. 26. 13.  8. 26. 32.  2. 21.]]


### Задание 3

#### Встроенная сортировка

In [30]:
a_np_sorted = np.sort(a)
counter = 0
a_np_s_b = np.zeros((m,n))

for i in range (m):
    for j in range (n):
        a_np_s_b[i][j] = a_np_sorted[counter]
        counter += 1

a_np_s_b

array([[ 2.,  2.,  3.,  4.,  5.,  6.,  7.,  7.,  8.,  8.],
       [ 8.,  8.,  9.,  9., 10., 11., 13., 13., 15., 18.],
       [19., 20., 20., 20., 20., 21., 21., 22., 22., 26.],
       [26., 28., 28., 32., 32., 32., 33., 33., 34., 34.]])

#### Выбором

In [32]:
# создаём функцию-сортировщик
def select (a = list):
    index = 0
    tech = 0
    for i in range (len(a)):
        index = i
        for j in range (i+1,len(a)):
            if a[j]<a[index] :
                index = j
        tech = a[index]
        a[index] = a[i]
        a[i] = tech
    
    return a


a_sort_select = select(a) # отсортированный массив

a_matrix_select = np.zeros((m,n)) # матрица

print(a_sort_select)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_select[i][j] = a_sort_select[counter]
        counter += 1
a_matrix_select # вывод матрицы

[2, 2, 3, 4, 5, 6, 7, 7, 8, 8, 8, 8, 9, 9, 10, 11, 13, 13, 15, 18, 19, 20, 20, 20, 20, 21, 21, 22, 22, 26, 26, 28, 28, 32, 32, 32, 33, 33, 34, 34]


array([[ 2.,  2.,  3.,  4.,  5.,  6.,  7.,  7.,  8.,  8.],
       [ 8.,  8.,  9.,  9., 10., 11., 13., 13., 15., 18.],
       [19., 20., 20., 20., 20., 21., 21., 22., 22., 26.],
       [26., 28., 28., 32., 32., 32., 33., 33., 34., 34.]])

#### Вставкой

#### Обменом

#### Шелла

In [ ]:
def shell(data):
    inc = len(data) // 2
    while inc:
        for i, el in enumerate(data):
            while i >= inc and data[i - inc] > el:
                data[i] = data[i - inc]
                i -= inc
            data[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
    return data


#### Турнирная

#### Быстрая сортировка

#### Пирамидальная