# Лабораторная работа №1
## Выполнил студент группы БВТ2001 Разумов Игорь Вячеславович
### Задание 1

In [1]:
print("Hello, world!")

Hello, world!


### Задание 2

In [2]:
from random import randint
import numpy as np
m, n , min_limit, max_limit = map(int, input("Введите числа:").split()) 
a = []
for i in range(m*n):
    a.append(randint(min_limit,max_limit))
counter = 0


counter = 0
a_np = np.zeros((m,n))
for i in range (m):
    for j in range (n):
        a_np[i][j] = a[counter]
        counter += 1
print ("Numpy матрица")
print(a_np)

Введите числа:4 6 12 45
Numpy матрица
[[17. 19. 33. 23. 45. 21.]
 [29. 26. 45. 24. 29. 42.]
 [38. 39. 14. 37. 25. 13.]
 [44. 38. 42. 42. 16. 44.]]


### Задание 3

#### Встроенная сортировка

In [3]:
a_np_sorted = np.sort(a)
counter = 0
a_np_s_b = np.zeros((m,n))

for i in range (m):
    for j in range (n):
        a_np_s_b[i][j] = a_np_sorted[counter]
        counter += 1

a_np_s_b

array([[13., 14., 16., 17., 19., 21.],
       [23., 24., 25., 26., 29., 29.],
       [33., 37., 38., 38., 39., 42.],
       [42., 42., 44., 44., 45., 45.]])

#### Выбором

In [4]:
# создаём функцию-сортировщик
def select (a = list):
    index = 0 # переменная минимального индекса
    tech = 0
    for i in range (len(a)): # идём по массиву
        index = i
        for j in range (i+1,len(a)): # находим минимальное значение
            if a[j]<a[index] :
                index = j
        tech = a[index] # меняем местами числа
        a[index] = a[i]
        a[i] = tech # эти 3 строчки можно упростить
    
    return a


a_sort_select = select(a) # отсортированный массив

a_matrix_select = np.zeros((m,n)) # матрица

print(a_sort_select)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_select[i][j] = a_sort_select[counter]
        counter += 1
a_matrix_select # вывод матрицы

[13, 14, 16, 17, 19, 21, 23, 24, 25, 26, 29, 29, 33, 37, 38, 38, 39, 42, 42, 42, 44, 44, 45, 45]


array([[13., 14., 16., 17., 19., 21.],
       [23., 24., 25., 26., 29., 29.],
       [33., 37., 38., 38., 39., 42.],
       [42., 42., 44., 44., 45., 45.]])

#### Вставкой

In [5]:
def insert (a = list):
    for i in range(1,len(a)-1): #идём по массиву
        znach = a[i]
        j = i - 1

        while j >= 0 and a[j] >= a[i]: # идём по отсортированной части
            a[j+1] = a[j]
            j -= 1
        a[j + 1] = znach
    return a

a_sort_insert = insert(a)

a_matrix_insert = np.zeros((m,n)) # матрица

print(a_sort_insert)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_insert[i][j] = a_sort_insert[counter]
        counter += 1
a_matrix_insert # вывод матрицы

[13, 14, 16, 17, 19, 21, 23, 24, 25, 26, 29, 29, 33, 37, 38, 38, 39, 42, 42, 42, 44, 44, 45, 45]


array([[13., 14., 16., 17., 19., 21.],
       [23., 24., 25., 26., 29., 29.],
       [33., 37., 38., 38., 39., 42.],
       [42., 42., 44., 44., 45., 45.]])

#### Обменом

#### Шелла

In [6]:
def shell(a):
    inc = len(a) // 2
    while inc:
        for i, el in enumerate(a):
            while i >= inc and a[i - inc] > el:
                a[i] = a[i - inc]
                i -= inc
            a[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
    return a

a_sort_shell = shell(a)

a_matrix_shell = np.zeros((m,n)) # матрица

print(a_sort_shell)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_shell[i][j] = a_sort_shell[counter]
        counter += 1
a_matrix_shell # вывод матрицы

[13, 14, 16, 17, 19, 21, 23, 24, 25, 26, 29, 29, 33, 37, 38, 38, 39, 42, 42, 42, 44, 44, 45, 45]


array([[13., 14., 16., 17., 19., 21.],
       [23., 24., 25., 26., 29., 29.],
       [33., 37., 38., 38., 39., 42.],
       [42., 42., 44., 44., 45., 45.]])

#### Турнирная

#### Быстрая сортировка

#### Пирамидальная